USE ROLE ACCOUNTADMIN;
USE WAREHOUSE HOL_WH;
USE DATABASE HOL_DB;
USE SCHEMA PUBLIC;

ALTER WAREHOUSE HOL_WH SET WAREHOUSE_SIZE = XLARGE WAIT_FOR_COMPLETION = TRUE;
CREATE OR REPLACE VIEW HourlyFlights AS
    SELECT 
        EXTRACT(HOUR FROM SCHEDULED_ARRIVAL_TIME_LOCAL) AS HourOfDay,
        COUNT(*) AS ArrivalFlightCount,
        0 AS DepartureFlightCount
    FROM 
        HOL_DB.PUBLIC.FLIGHT_STATUS_DATA_CLEANING
    WHERE 
        ARRIVAL_IATA_AIRPORT_CODE = 'JFK'
    GROUP BY 
        EXTRACT(HOUR FROM SCHEDULED_ARRIVAL_TIME_LOCAL)
    
    UNION ALL
    
    SELECT 
        EXTRACT(HOUR FROM SCHEDULED_DEPARTURE_TIME_LOCAL) AS HourOfDay,
        0 AS ArrivalFlightCount,
        COUNT(*) AS DepartureFlightCount
    FROM 
        HOL_DB.PUBLIC.FLIGHT_STATUS_DATA_CLEANING
    WHERE 
        DEPARTURE_IATA_AIRPORT_CODE = 'JFK'
    GROUP BY 
        EXTRACT(HOUR FROM SCHEDULED_DEPARTURE_TIME_LOCAL);

CREATE OR REPLACE VIEW RankedHours AS
    SELECT 
        HourOfDay,
        SUM(ArrivalFlightCount) AS ArrivalFlightCount,
        SUM(DepartureFlightCount) AS DepartureFlightCount
    FROM 
        HourlyFlights
    GROUP BY
        HourOfDay;

ALTER WAREHOUSE HOL_WH SET WAREHOUSE_SIZE = XSMALL;